### ISSUE TITLE
Shopify-cli doesn't work for me

### ISSUE THREAD

**Issue by beatlecz** [Shopify/shopify-app-cli#779] opened 2020-07-27 13:55 UTC
# Issue summary

I am not able to run the clie anymore. Got an error related to fetching some information about my partners program organization. I suspect that the problem has been occuring since the time I has been added to another organization.

Here is the error when I try to serve the app:
```
✗ An unexpected error occurred on Shopify.
Traceback (most recent call last):
        13: from /usr/local/Cellar/shopify-cli/1.0.2/src/bin/shopify:30:in `<main>'
        12: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        11: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        10: from /usr/local/Cellar/shopify-cli/1.0.2/src/bin/shopify:31:in `block in <main>'
         9: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/entry_point.rb:39:in `call'
         8: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/monorail.rb:32:in `log'
         7: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
         6: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/executor.rb:13:in `call'
         5: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/executor.rb:13:in `each'
         4: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/executor.rb:14:in `block in call'
         3: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/task.rb:7:in `call'
         2: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/tasks/ensure_dev_store.rb:10:in `call'
         1: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/tasks/ensure_dev_store.rb:31:in `shop'
/usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/partners_api/organizations.rb:7:in `fetch_all': undefined method `[]' for nil:NilClass (NoMethodError)
```

- App type: Public
- Operating System: OSX
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by tanema** [comment] 2020-07-27 14:02
This is a duplicate of #732 please search issues before opening one.

Try running `shopify logout` and trying again. This error happens when you have might not fully signed up with that organization and the CLI is expecting to find one. We are working on a fix.

**Closed** 2020-07-27 14:02 UTC

**Comment by beatlecz** [comment] 2020-07-27 14:05
To be clear. I have already developing an app for last 3 months. It has been working all the time until last wee. I have tried to logout multiple times. Also reinstall cli to latest versions. Without success.

**Comment by tanema** [comment] 2020-07-27 14:18
Okay I will try to rush the fix through ASAP
