### ISSUE TITLE
on shopify serve ✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok f

### ISSUE THREAD

**Issue by viveksakpal** [Shopify/shopify-app-cli#892] opened 2020-10-01 06:59 UTC
# Issue summary

Write a short description of the issue here ↓
After installing shopify cli on shopify serve 
i get this error ✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok 

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.shopify create node 
2.project name
3.select public
4.project files get generated
5.on shopify serve
6.✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:public
- Operating System:mac os
- Shell:zsh
- Ruby version (ruby -v):2.6.3p62

**Comment by paulomarg** [comment] 2020-10-01 13:48
Hi @viveksakpal, thanks for reporting this!

Can you please confirm which version of the CLI you were running?

Also, what does running `killall -9 ngrok` return?

**Comment by viveksakpal** [comment] 2020-10-01 13:51
1. Shopify cli 1.2.0
2. And it does not return anything!!

**Comment by viveksakpal** [comment] 2020-10-01 14:01
It's return no maching processes belonging to you were found

**Comment by paulomarg** [comment] 2020-10-01 15:43
This is curious, I can only see this happening if `shopify tunnel` was running under a different user (maybe you started it with `sudo` at some point?), because the CLI would then have to detect that the tunnel is running but not be able to kill the process.

I tested that scenario locally and I got the same error message you did. My steps:

1. `sudo shopify tunnel start`
2. `shopify tunnel stop`
  2.1. ngrok tunnel could not be stopped. Try running killall -9 ngrok
3. `sudo shopify tunnel stop`
  3.1. ngrok tunnel stopped

You could check if the tunnel is running for any user with `ps aux | grep ngrok`. If that is the case, you could try `sudo shopify tunnel stop`.

Hope this helps!

**Comment by viveksakpal** [comment] 2020-10-02 02:47
. It shows Ngork is not running 
. I suspect the problem is when I run Shopify serve its not able to start ngrok so it's shows start your app your app is not running and no url has been set  and it says try running Shopify serve.
. My default app is getting tagged as draft(does it helps?)

**Comment by paulomarg** [comment] 2020-10-02 12:54
That makes sense, maybe ngrok is failing to even start. You can test if it works by running:
```
~/.cache/shopify/ngrok http -inspect=false -log=stdout -log-level=debug 8081
```

**Comment by viveksakpal** [comment] 2020-10-02 13:06
It's showing permission denied by zsh  even after sudo

**Comment by viveksakpal** [comment] 2020-10-02 13:09
How does Shopify serve and ngrok gets connected/triggered is there a specific way where I need to keep the ngrok  file or it's path somewhere?

**Comment by viveksakpal** [comment] 2020-10-02 13:13
I'm doing this for node config if it helps!

**Comment by paulomarg** [comment] 2020-10-02 13:17
The command I pasted before is actually what the CLI will be running in the background when it starts up ngrok, so we know why it's failing to set you up now.

Can you check that you have execution rights to that folder and file? You can run `ls -la ~/.cache/shopify` to see if you have the `x` rights on for them.

**Comment by viveksakpal** [comment] 2020-10-02 13:24
Ngrok does not have x it has --rw-r--r--@
And .db.pstore has --rw-r--r--

**Comment by paulomarg** [comment] 2020-10-02 13:28
Ok, so that is why it's failing to start. Could you please try running `chmod +x ~/.cache/shopify/ngrok` and retry the command? If that still fails, you can make sure that you have execution rights on the folder itself: `chmod +x ~/.cache/shopify`

**Comment by viveksakpal** [comment] 2020-10-02 13:45
In the both case it shows the same error 
Ngrok tunnel could not be stopped. Try running killall -9 ngrok

After doing that it's reflects on same message : no maching process were belong to you were found.

**Comment by viveksakpal** [comment] 2020-10-02 14:08
How does Shopify knows the path of ngrok cli? Cause ngrok can be only accessed from with in its folder.

**Comment by paulomarg** [comment] 2020-10-02 15:05
The CLI will always try to run the command I pasted before:
```
~/.cache/shopify/ngrok http -inspect=false -log=stdout -log-level=debug 8081
```

Unfortunately, at this point it's hard for us to tell what is going wrong as the problem is not with the CLI itself, but you'll have to fix the permission issues you're getting.

You should make sure that you've added the `x` permissions for both the `~/.cache/shopify` folder and `ngrok` file, but other than that unfortunately we won't be able to help. Once that works, you'll be able to serve your app.

**Comment by viveksakpal** [comment] 2020-10-02 18:13
@paulomarg  thanks for effort I got the solution
I deleted ngork file from the ~/.cache/Shopify/
And run Shopify serve its auto download ngrok.zip and unzip it and made it worked.🤩✌️😉

**Comment by paulomarg** [comment] 2020-10-02 18:22
That's great @viveksakpal. I'll go ahead and close this issue then. Happy coding!

**Closed by paulomarg** 2020-10-02 18:22 UTC

**Comment by brandondougherty** [comment] 2022-01-19 22:22
This occurred for me because i didn't verify my ngrok account email, was super confusing.

**Comment by shawn-simon-developer** [comment] 2022-01-26 19:12
> This occurred for me because i didn't verify my ngrok account email, was super confusing.

Same for me! Thanks for the help.
