### ISSUE TITLE
Shopify serve not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by PeteButler** [Shopify/shopify-app-cli#526] opened 2020-04-20 10:00 UTC
I have seen similar issues raised and closed saying that it had been fixed and was due to incorrectly set Shopify app secret, however the app secret key has been created with the Shopify create command and verified as being correct in the .env file. I also tried manually to create an app, using the Shopify tutorials for creating node and react apps and encountered the same issue

```
➜  Code mkdir shopify-app-testing
➜  Code cd shopify-app-testing 
➜  shopify-app-testing shopify create
? What type of project would you like to create? (You chose: Node.js App)
? App Name                                                                                                                                             
> App Development Test                                                                                                                                 
? What type of app are you building? (You chose: Public: An app built for a wide merchant audience.)
? Select organization (You chose: Artisan Test Account)
? Select a Development Store (You chose: artisan-test-dev1.myshopify.com)
✓ node v10.15.2                                                                                                                                        
✓ npm 6.4.1                                                                                                                                            
┏━━ Cloning into app_development_test... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Cloning into 'app_development_test'...                                                                                                               
┃ remote: Enumerating objects: 23, done.        
remote: Counting objects: 100% (23/23), done.        
remote: Compressing objects: 100% (23/23), done.        
remote: Total 1068 (delta 13), reused 0 (delta 0), pack-reused 1045        
Receiving objects: 100% (1068/1068), 1.76 MiB | 2.36 MiB/s, done.
Resolving deltas: 100% (717/717), done.
┃                                                                                                                                                  100%
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.52s) ━━
✓ Cloned app in app_development_test
┏━━ Installing dependencies with npm... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✓ 37 npm dependencies installed
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (21.44s) ━━
✓ Dependencies installed
✓ .env saved to project root
✓ App Development Test was created in your Partner Dashboard https://partners.shopify.com/1384232/apps/3701917
⭑ Run shopify serve to start a local server
⭑ Then, visit https://partners.shopify.com/1384232/apps/3701917/test to install App Development Test on your Dev Store
➜  app_development_test shopify serve 
zsh: correct 'serve' to 'server' [nyae]? n
#<Thread:0x000055922bb1d588@/home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:43 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
	6: from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
	5: from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
	4: from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
	3: from /home/peter/.shopify-app-cli/lib/shopify-cli/tunnel.rb:60:in `block in install'
	2: from /home/peter/.shopify-app-cli/lib/shopify-cli/context/system.rb:51:in `system'
	1: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
/home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn': no implicit conversion of nil into String (TypeError)
✗ Installing ngrok...
┏━━ Task Failed: Installing ngrok... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ TypeError: no implicit conversion of nil into String
┃ 	from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn'
┃ 	from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
┃ 	from /home/peter/.shopify-app-cli/lib/shopify-cli/context/system.rb:51:in `system'
┃ 	from /home/peter/.shopify-app-cli/lib/shopify-cli/tunnel.rb:60:in `block in install'
┃ 	from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
┃ 	from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
┃ 	from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
┃ 	from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
┣━━ STDOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┣━━ STDERR ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.0s) ━━
x ngrok tunnel stopped
This command ran with ID: 16408
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	26: from /home/peter/.shopify-app-cli/bin/shopify:36:in `<main>'
	25: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	24: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	23: from /home/peter/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	22: from /home/peter/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
	21: from /home/peter/.shopify-app-cli/lib/shopify-cli/core/monorail/log.rb:29:in `invocation'
	20: from /home/peter/.shopify-app-cli/lib/shopify-cli/core/monorail/log.rb:45:in `event'
	19: from /home/peter/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
	18: from /home/peter/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
	17: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	16: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	15: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	14: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	13: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
	12: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	11: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	10: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	 9: from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	 8: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	 7: from /home/peter/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 6: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 5: from /home/peter/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 4: from /home/peter/.shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
	 3: from /home/peter/.shopify-app-cli/lib/project_types/node/commands/serve.rb:15:in `call'
	 2: from /home/peter/.shopify-app-cli/lib/shopify-cli/tunnel.rb:37:in `start'
	 1: from /home/peter/.shopify-app-cli/lib/shopify-cli/tunnel.rb:68:in `fetch_url'
/home/peter/.shopify-app-cli/lib/shopify-cli/tunnel.rb:72:in `rescue in fetch_url': Unable to fetch external url (ShopifyCli::Tunnel::FetchUrlError)
➜  app_development_test 
```

**Comment by tanema** [comment] 2020-04-20 13:07
Yes sorry this seems like a duplicate of https://github.com/Shopify/shopify-app-cli/issues/519 we will be looking into this soon.

**Closed by tanema** 2020-04-20 13:07 UTC
