### ISSUE TITLE
v1 has killed the 'shopify' command: "shopify command is no longer bundled with shopify_api."

### ISSUE THREAD

**Issue by gavinsmith** [Shopify/shopify-app-cli#742] opened 2020-07-15 15:37 UTC
Migrating to v1 by following the migration guide has me in a state with this error: 

```
shopify command is no longer bundled with shopify_api.
if you need these tools, install the shopify_cli gem
```

I have closely followed the [migration guide](https://shopify.github.io/shopify-app-cli/getting-started/migrate/) multiple times, double- and triple-checked my bash profile files for Shopify-related lines and removed them, I've un-and re-installed the `shopify-cli` gem multiple times, etc.

I no longer have `~/.shopify-app-cli/shopify.sh` as deleting it was part of the migration steps, I'm not sure if it's supposed to have been replaced.

This is on MacOS 10.15.5, Ruby 2.7.0 installed via RVM.

Has the command changed? Something else I'm missing? I know at least one other with the same issue.

**Comment by mkevinosullivan** [comment] 2020-07-15 15:42
Hi Gavin,

With the installed version of the App CLI, you should have a `/usr/local/bin/shopify` which is the location of the CLI command.  However, your path is picking up an old, deprecated `shopify` command from the `shopify_api` gem first, before the `shopify` command in `/usr/local/bin`.

We also released a new version of the `shopify_api` gem yesterday that removes the `shopify` command from that gem, so we recommend updating that gem also.

In any case, the App CLI `shopify` command should be located at `/usr/local/bin/shopify`.

Regards,
Kevin.

**Comment by tanema** [comment] 2020-07-15 15:53
@gavinsmith you can reset this by running `gem uninstall shopify_api` if it says that it is not installed check which ruby it is installed in `which shopify` and then switch to that version and uninstall the gem.

**Comment by gavinsmith** [comment] 2020-07-15 16:21
uninstalling shopify_api and re-installing gets me to an RVM related error I've never seen:

`.rvm/gems/ruby-2.7.0/gems/shopify-cli-1.0.0/lib/shopify-cli/core/entry_point.rb:11:in `initialize': The given fd is not accessible because RubyVM reserves it (ArgumentError)`

`/usr/local/bin/shopify` indeed exists and points to the correct version of the gem

**Comment by tanema** [comment] 2020-07-15 16:54
Have you restarted your shell? Otherwise uninstall/reinstall probably.  We have not seen that error in our testing.

**Comment by gavinsmith** [comment] 2020-07-15 17:16
I have, and I've uninstalled and reinstalled everything related as best asI can tell. I'll keep poking away.

**Comment by awd** [comment] 2020-07-15 18:24
Hello - I am having the same problem on my machine as well. 

In the terminal window:
`which shopify` => `/usr/local/bin/shopify`

Running any `shopify` command: 
`shopify serve`

```
Traceback (most recent call last):
	6: from /usr/local/Cellar/shopify-cli/1.0.0/src/bin/shopify:30:in `<main>'
	5: from /usr/local/Cellar/shopify-cli/1.0.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	4: from /usr/local/Cellar/shopify-cli/1.0.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	3: from /usr/local/Cellar/shopify-cli/1.0.0/src/bin/shopify:31:in `block in <main>'
	2: from /usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `call'
	1: from /usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `open'
/usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `initialize': The given fd is not accessible because RubyVM reserves it (ArgumentError)
```

**Comment by awd** [comment] 2020-07-15 18:26
I should add I am also running ruby 2.7.0 - likely what version you want to test it against locally.
`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]`

**Comment by tanema** [comment] 2020-07-15 20:27
Please see @paulomarg attached PR. We were able to reproduce this. This is specifically a case with RVM support. We should have this fixed soon, sorry about the inconvenience.

**Comment by tanema** [comment] 2020-07-15 20:36
Since this is now a duplicate of #740 we will track further update on that issue. It will remain open until we can confirm that it is working again for you.

**Closed by tanema** 2020-07-15 20:36 UTC
