### ISSUE TITLE
Can't register the APP_SUBSCRIPTIONS_ADD/UPDATE/DELETE

### ISSUE THREAD

**Issue by sudhindra** [Shopify/shopify-app-cli#311] opened 2019-09-17 08:15 UTC
# Issue summary
Can't register the APP_SUBSCRIPTIONS_ADD/UPDATE/DELETE
Write a short description of the issue here ↓
Can't register the APP_SUBSCRIPTIONS_ADD/UPDATE/DELETE
seeing error on console 
Failed to register webhook { userErrors:
┃    [ { field: [Array],
┃        message:
┃         'You cannot create a webhook subscription with the specified topic' } ],
┃   webhookSubscription: null }

try to solve by using https://github.com/Shopify/shopify-app-cli/issues/302 but still issue persisits

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by tanema** [comment] 2019-09-17 14:01
duplicate of #302

**Closed by tanema** 2019-09-17 14:01 UTC
