### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by tyx** [Shopify/shopify-app-cli#315] opened 2019-09-24 15:12 UTC
# Issue summary

Hello, I try to install this tool but the process is failing when trying to source the shopify.sh apparently

## Expected behavior

I would expect to have the shopify CLI installed

## Actual behavior

Here is a screenshot of what happens

https://prnt.sc/pad4qw

## Specifications

- App type: not sure
- Operating System:  I am on ubuntu through WSL 
- Shell: bash
- Ruby version (ruby -v):  ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by tanema** [comment] 2019-09-25 11:40
Hey @tyx Did you manage to get it working? Can you `cd ~/.shopify-app-cli` and `git pull` I am worried that the script is corrupted in some way because that error does not make that much sense.

**Comment by tyx** [comment] 2019-09-25 12:58
Hello @tanema 

```
tim@P386:~/.shopify-app-cli$ git pull
Already up to date.
```

As I noticed that my .bash_profile was modified, i tried:
 ```
$ source ~/.shopify-app-cli/shopify.sh
: command not found
: command not found
: command not found
bash: /home/tim/.shopify-app-cli/shopify.sh: line 14: syntax error near unexpected token `$'in\r''
'ash: /home/tim/.shopify-app-cli/shopify.sh: line 14: `case "${__shellname}" in
```

**Comment by tanema** [comment] 2019-09-25 13:12
can you run `bash --version`? It seems like you are running this in bash and there is a syntax error but I cannot understand how that could be.

**Comment by tyx** [comment] 2019-09-25 13:27
```
$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by tanema** [comment] 2019-09-25 13:51
This is so strange. It works for me on bash 2.2.23 so it should work for you. I have no idea, I would recommend deleting your installation (remember to remove the source line from your bashrc) and trying to reinstall it.

Also could you post a snippet of the shopify.sh file before you delete it? Maybe I can see something that way.

**Comment by tyx** [comment] 2019-09-25 13:57
I already tried to install it twice, also through a docker container same result : (

here is the `shopify.sh`
https://gist.github.com/tyx/a14543aafb188b9574e2d3cdf3e3d65e

**Comment by lemonadecreative** [comment] 2020-04-08 03:26
Same issue for me. Tried running several versions of Ruby to see if that'd help, no go. 

Any luck with a fix here?

**Comment by tanema** [comment] 2020-04-08 12:49
Can you check what version of bash you are running?

**Comment by lemonadecreative** [comment] 2020-04-08 22:52
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

**Comment by lemonadecreative** [comment] 2020-04-08 23:53
Also switched to zsh and tried installing again, but similar issue. 

┏━━ 🦄  1/2: Installing Prerequisites ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✔︎ Already have XCode Command Line Tools
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━ 🦄  2/2: Installing shopify-app-cli ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Cloning Shopify/shopify-app-cli into /Users/[username]/.shopify-app-cli
┃ Cloning into '.'...
┃ ✔︎ cloned shopify/shopify-app-cli
┃ ✔︎ shell set up for shopify-app-cli
┃ ✔︎ NOTE: added a line to the end of /Users/[username]/.zshrc
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify-app-cli is installed!
┃ Run shopify help to see what you can do, or read https://github.com/Shopify/shopify-app-cli.
┃ To start developing on shopify, for example:
┃   * run shopify create project <appname>
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
/Users/[username]/.shopify-app-cli/shopify.sh:6: command not found: ^M
/Users/[username]/.shopify-app-cli/shopify.sh:9: command not found: ^M
/Users/[username]/.shopify-app-cli/shopify.sh:13: command not found: ^M
/Users/[username]/.shopify-app-cli/shopify.sh:14: parse error near `in^M'

[username]@Matthews-MacBook-Pro-3 ~ % shopify help
shopify command is no longer bundled with shopify_api.
if you need these tools, install the shopify_cli gem

**Comment by tanema** [comment] 2020-04-09 15:18
That error at the end is because of an old installation of `shopify_app` you can remove it by running `gem uninstall shopify_app` Also can you please check the shopify.sh file to see if it is corrupted?

**Comment by lemonadecreative** [comment] 2020-04-09 21:33
@tanema still seeing the same issue. 

How would I know if it's corrupt? I don't see any issues with the file and I downloaded it directly using the script detailed in this installation process. If it's corrupt, wouldn't it be an issue with the repo that would need fixing?

Here's the contents of that file…
`#!/bin/sh
# shellcheck disable=1001,1012,2039,1090
# 1001,1012 stop complaints about '\awk' syntax to bypass aliases.
# 2039 stops complaints about array references not being POSIX.
# 1090 stops complaints about sourcing non-constant paths.

# We program rather defensively here, since this is evaluated in the context of
# the user's shell, and there can be pretty aggressive configuration there.

# This must be outside of the function context for $0 to work properly
__shell="$(\ps -p $$ | \awk 'NR > 1 { sub(/^-/, "", $4); print $4 }')"
__shellname="$(basename "${__shell}")"

case "${__shellname}" in
  zsh)  __shopify_cli_source_dir="$(\dirname "$0:A")" ;;
  bash) __shopify_cli_source_dir="$(builtin cd "$(\dirname "${BASH_SOURCE[0]}")" && \pwd)" ;;
  *)
    >&2 \echo "shopify-cli is not compatible with your shell (${__shell})"
    \return 1
    ;;
esac

#### Handlers for bin/dev-shell-support environment manipulation
#### See bin/dev-shell-support for documentation.
shopify_cli__source() { source "$1"; }
shopify_cli__setenv() { export "$1=$2"; }
shopify_cli__append_path() { export "PATH=${PATH}:$1"; }
shopify_cli__lazyload() { type "$1" >/dev/null 2>&1 || eval "$1() { source $2 ; $1 \"\$@\"; }"; }
shopify_cli__prepend_path() {
  PATH="$(
    /usr/bin/awk -v RS=: -v ORS= -v "prepend=$1" '
      BEGIN         { print prepend }
                    { gsub(/\n$/,"", $0) }
      $0 != prepend { print ":" $0 }
    ' <<< "${PATH}"
  )"
  export PATH
}

while read -r line; do
  eval "${line}"
done < <("${__shopify_cli_source_dir}/bin/shopify-cli-shell-support" env "${__shellname}")

unset -f shopify_cli__source
unset -f shopify_cli__setenv
unset -f shopify_cli__append_path
unset -f shopify_cli__prepend_path
unset -f shopify_cli__lazyload

### END MUCKING WITH THE USER'S ENVIRONMENT

__mtime_of_shopify_cli_script="$(\date -r "${__shopify_cli_source_dir}/shopify.sh" +%s)"

shopify() {
  # reload __shopify_cli__ function
  local current_mtime
  current_mtime="$(\date -r "${__shopify_cli_source_dir}/shopify.sh" +%s)"

  if [[ "${current_mtime}" != "${__mtime_of_shopify_cli_script}" ]]; then
    . "${__shopify_cli_source_dir}/shopify.sh"
  fi
  __shopify_cli__ "$@"
}

__shopify_cli__() {
  for cmd in chruby_auto rvm rbenv iterm2_preexec; do
    if command -v "${cmd}" >/dev/null 2>&1 ; then
      export "SHOPIFY_CLI_CONFLICTING_TOOL_${cmd}=1"
    fi
  done

  # https://discourse.shopify.io/t/running-dev-up-changes-the-display-language-of-apple-terminal/1556
  export LANG="${LANG-en_US.UTF-8}"
  export LANGUAGE="${LANGUAGE-en_US.UTF-8}"
  export LC_ALL="${LC_ALL-en_US.UTF-8}"

  local bin_path
  bin_path="${__shopify_cli_source_dir}/bin/shopify"

  local tmpfile
  tmpfile="$(\mktemp -u)" # Create a new tempfile

  exec 9>"${tmpfile}" # Open the tempfile for writing on FD 9.
  exec 8<"${tmpfile}" # Open the tempfile for reading on FD 8.
  \rm -f "${tmpfile}" # Unlink the tempfile. (we've already opened it).

  local return_from_shopify_cli
  local with_gems
  local install_dir="$HOME/.shopify-cli"
  if [[ "${__shopify_cli_source_dir}" == "${install_dir}" ]] || [ ! -t 0 ]; then
    with_gems="FALSE"
  else
    with_gems="TRUE"
  fi
  if [[ "$1" == "--with-gems" ]]; then
    shift
    with_gems="TRUE"
  elif [[ "$1" == "--without-gems" ]]; then
    shift
    with_gems="FALSE"
  fi

  if [[ ${with_gems} == "TRUE" ]]; then
    /usr/bin/env ruby "${bin_path}" "$@"
  else
    "${bin_path}" "$@"
  fi
  return_from_shopify_cli=$?

  local finalizers
  finalizers=()

  local fin
  while \read -r fin; do
    finalizers+=("${fin}")
  done <&8

  exec 8<&- # close FD 8.
  exec 9<&- # close FD 9.

  for fin in "${finalizers[@]}"; do
    case "${fin}" in
      cd:*)
        # shellcheck disable=SC2164
        cd "${fin//cd:/}"
        ;;
      setenv:*)
        # shellcheck disable=SC2163
        export "${fin//setenv:/}"
        ;;
      reload_shopify_cli_from:*)
        # Force chruby to re-scan next time it runs.
        unset -f chruby 2>/dev/null
        source "${fin//reload_shopify_cli_from:/}/shopify.sh"
        ;;
      *)
        ;;
    esac
  done

  \return ${return_from_shopify_cli}
}

# . "${__shopify_cli_source_dir}/sh/hooks/hooks.${__shellname}"
`

**Comment by tanema** [comment] 2020-04-13 17:54
> If it's corrupt, wouldn't it be an issue with the repo that would need fixing?

Yes that is why I am trying to figure out what is happening. It seems like is an issue with windows. oh-my-zsh has seen similar issues that were mitigated with `dos2unix` https://github.com/ohmyzsh/ohmyzsh/issues/1363 I would recommend trying to change your gitconfig as was recommended in that thread and trying to re-install the cli

**Comment by lemonadecreative** [comment] 2020-04-14 18:36
@tanema that helped get the cli installed without any issues, but when trying to create a project I ran into a new error.

`~/Sites » shopify create project shopify-app-test
/Users/[username]/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Users/[username]/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:151: syntax error, unexpected << (SyntaxError)
            raise ArgumentError, <<~EOF
                                   ^
/Users/[username]/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:165: syntax error, unexpected keyword_ensure, expecting keyword_end
/Users/[username]/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:227: syntax error, unexpected end-of-input, expecting keyword_end`

**Comment by tballast** [comment] 2020-04-14 19:15
I'm seeing the exact same issue. WSL in Windows 10. 

```
tballast@DRAGONS-DEN:~$ eval "$(curl -sS https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh)"
┏━━ 🦄  1/2: Installing Prerequisites ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✔︎ Successfully installed shopify-app-cli prerequisites
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━ 🦄  2/2: Installing shopify-app-cli ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Cloning Shopify/shopify-app-cli into /home/tballast/.shopify-app-cli
┃ Cloning into '.'...
┃ ✔︎ cloned shopify/shopify-app-cli
┃ ✔︎ shell set up for shopify-app-cli
┃ ✔︎ NOTE: added lines to the end of ~/.bash_profile and ~/.bashrc
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify-app-cli is installed!
┃ Run shopify help to see what you can do, or read https://github.com/Shopify/shopify-app-cli.
┃ To start developing on shopify, for example:
┃   * run shopify create project <appname>
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
: command not found
: command not found
: command not found
bash: /home/tballast/.shopify-app-cli/shopify.sh: line 14: syntax error near unexpected token `$'in\r''
'ash: /home/tballast/.shopify-app-cli/shopify.sh: line 14: `case "${__shellname}" in
```

Bash Version: 4.4.20(1)-release

**Comment by lemonadecreative** [comment] 2020-04-14 20:09
@tballast can you edit your .gitconfig and remove the `autocrlf = true`, then rerun the install command to see if you're still having trouble. It installed fine after I edited mine, but creating a new project had issues still. Wondering if you'll see the same.

**Comment by tanema** [comment] 2020-04-14 20:14
Hi @lemonadecreative thanks for sticking it out! Can you make sure that when you delete the whole `/Users/[username]/.shopify-app-cli` folder and try the install again? It seems like it is saying that there is invalid ruby code from code that is in our vendor folder, so that is unlikely unless again, the code was misinterpreted.

**Comment by lemonadecreative** [comment] 2020-04-14 20:20
@tanema yep, I did that and was able to run the install just fine. The issue is when creating the project with `shopify create project [project-name]`, it fails with the errors I mentioned [here](https://github.com/Shopify/shopify-app-cli/issues/315#issuecomment-613611232)

**Comment by tballast** [comment] 2020-04-15 07:22
@lemonadecreative When I ran your command it complained to me that I didn't specify a proper project type. 
```
tballast@DRAGONS-DEN:~/git/tballast/shopify/shopify-app-cli-app$ shopify create project shopify-project
/home/tballast/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/tballast/.shopify-app-cli/bin in PATH, mode 040777
? Would you like to enable auto updates for Shopify App CLI? (You chose: yes)
Updating shopify-cli...done!
/home/tballast/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/tballast/.shopify-app-cli/bin in PATH, mode 040777
? Would you like to enable anonymous usage reporting?
If you select “Yes”, we’ll collect data about which commands you use and which errors you encounter.
Sharing this anonymous data helps Shopify improve this tool.
? Would you like to enable anonymous usage reporting?
If you select “Yes”, we’ll collect data about which commands you use and which errors you encounter.
Sharing this anonymous data helps Shopify improve this tool.
 (You chose: yes)
Error: invalid app type project
Create a new project.
  Usage: shopify create [ node | rails ]
```

running `shopify create node my-proj` got me past that point.

**Comment by tballast** [comment] 2020-04-15 09:05
As a workaround, I was able to run 

`shopify tunnel start`
`shopify tunnel stop`

and then it worked.

**Comment by lemonadecreative** [comment] 2020-04-15 15:13
@tballast Interesting that worked for you. 

@tanema 
I'm still seeing the error running both:
`shopify create rails [project-name]`
`shopify create node [project-name]`

**Comment by tanema** [comment] 2020-04-15 15:24
Yes is seems like something is still wrong with your line-endings. Ruby is raising a syntax error on code that works for others. 

Can you open `/Users/[username]/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb` and see what it looks like?

**Comment by lemonadecreative** [comment] 2020-04-15 18:47
@tanema I've been reviewing it to see if I can locate an issue, but I don't know what this code is doing so hard for me to deduce it. Any thoughts? Not sure why I'd seemingly be the only one experiencing this.

This is where that error is coming from…
![image](https://user-images.githubusercontent.com/20567992/79376223-7745d380-7f1f-11ea-8f40-a26041533c15.png)

**Comment by lemonadecreative** [comment] 2020-04-15 19:45
@tanema @tballast guys, thanks for your help here. I decided to wipe ruby from my system and completely reinstall. It worked. Not the ideal approach but maybe something in my system was corrupt.

Again, thanks.

**Comment by mkevinosullivan** [comment] 2020-09-18 19:13
Closing this issue as the issues raised were on the beta version of the CLI.  Since v1.0.0 was launched (mid-July 2020), the CLI:
- is no longer installed via a shell script
- no longer uses a shell shim to run
- requires a version of Ruby at least 2.5 or above

**Closed by mkevinosullivan** 2020-09-18 19:13 UTC
Labels: installation/stability
