### ISSUE TITLE
Turning on Embedded App from Development Store admin dashboard redirects to host url and then redirects back to admin dashboard

### ISSUE THREAD

**Issue by hotmailbelike** [Shopify/shopify-app-cli#980] opened 2020-11-19 08:07 UTC
# Issue summary

I am using shopify-app-cli to build a node.js project. I just created a simple embedded app to test it on the development store. The issue is that, when I open the app from the store admin dashboard, it redirects to the host url (happened for both ngrok url and heroku url) and then redirects back to the admin dashboard.
You can have a clearer view of the problem here: https://www.loom.com/share/543ba7db67444e0686dcc748fdefdd38

## Expected behavior

It should not have redirected me outside the admin dashboard and redirect back.
It should have stayed inside the admin dashboard and not redirect anywhere else.

## Actual behavior

When opening the app from the development store it gets redirected to the host url and then redirects back to the admin dashboard.

## Steps to reproduce the problem

1. Install App to development store
1. Logout of Store 
1. Login to Store again
1. Go to Apps section
1. Open the app

**Comment by paulomarg** [comment] 2020-11-19 14:31
Hi @hotmailbelike!

That is the normal behaviour for apps, the redirect is a necessary step. In order to build a session for your store in the app, it needs to go through the OAuth process, which involves redirecting the user to Shopify to install the app (or just create the session if it was already installed).

Once the app has performed OAuth and created the session, page loads will no longer require a redirect and will load directly.

You can find more information on how the OAuth process works in our [OAuth tutorial](https://shopify.dev/tutorials/authenticate-a-public-app-with-oauth).

I'm closing this issue since there are no changes to be made, as this is the expected behaviour, but thank you for taking the time to report this!

**Closed by paulomarg** 2020-11-19 14:31 UTC

**Comment by hotmailbelike** [comment] 2020-11-23 13:56
Thanks a lot!
