### ISSUE TITLE
new shopify cli 1.0.0 installed but got error 

### ISSUE THREAD

**Issue by ShirasuGyoza** [Shopify/shopify-app-cli#740] opened 2020-07-15 09:51 UTC
# Issue summary
I've just migrated new version from old version according to https://shopify.github.io/shopify-app-cli/getting-started/migrate/
After installing, the directory "~/.shopify-app-cli/" doesn't generated and displayed error when I try any `shopify` command.

error:
```
Traceback (most recent call last):
        6: from /usr/local/Cellar/shopify-cli/1.0.0/src/bin/shopify:30:in `<main>'
        5: from /usr/local/Cellar/shopify-cli/1.0.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        4: from /usr/local/Cellar/shopify-cli/1.0.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        3: from /usr/local/Cellar/shopify-cli/1.0.0/src/bin/shopify:31:in `block in <main>'
        2: from /usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `call'
        1: from /usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `open'
/usr/local/Cellar/shopify-cli/1.0.0/src/lib/shopify-cli/core/entry_point.rb:11:in `initialize': The given fd is not accessible because RubyVM reserves it (ArgumentError)
```

## Expected behavior
generate /.shopify-app-cli/ and then I can use `shopify` command

## Actual behavior
not generate /.shopify-app-cli/ and error displayed

## Steps to reproduce the problem

1. uninstall the old one. `$ rm -rf ~/.shopify-app-cli/` and then commented out the line I found in `~/.zshrc` 
1. install new version. `$ brew tap shopify/shopify` then `$ brew install shopify-cli`
1. run `shopify version` to display error message

## Specifications

- App type: 1.0.0 
- Operating System: macOS Catalina 10.15.5
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by gfscott** [comment] 2020-07-15 12:50
I also had this issue, but I resolved it by restarting the shell session. That cleared out the old CLI references and started using the new version. There are a few ways to restart:

- Just quit your terminal app and then start it again
- Run [`exec $SHELL`](https://unix.stackexchange.com/a/543543) to restart the shell environment without having to quit the terminal
- Since you're running zsh, run [`source ~/.zshrc`](https://kb.iu.edu/d/aeee)

Let us know if restarting fixes it!

**Comment by awd** [comment] 2020-07-15 18:46
We've got two threads with the same errors happening. 
https://github.com/Shopify/shopify-app-cli/issues/742

FYI - restarted, did the shell things, still no luck on any of this. :/

**Comment by tanema** [comment] 2020-07-15 20:27
Please see @paulomarg attached PR. We were able to reproduce this. This is specifically a case with RVM support. We should have this fixed soon, sorry about the inconvenience.

**Comment by tanema** [comment] 2020-07-15 20:35
I am just going to re-open this until we can confirm that it has fixed your issue after release.

**Comment by paulomarg** [comment] 2020-07-15 20:48
Release v1.0.1 is out now. Could you please upgrade and see if that fixes the issue for you?

**Comment by awd** [comment] 2020-07-15 21:01
Thanks @tanema + @paulomarg !!!

I've re-installed via brew - but looks like a `$PATH` issue where the `shopify_api` gem was trying to own the `shopify` command line.

Updating `.zshrc` with `/usr/local/bin` before everything else seems to work -> `export PATH="/usr/local/bin:$PATH:$HOME/.rvm/bin"`

Will the `shopify` command be pulled out of the gems in an upcoming version? 
`shopify_app` wants `shopify_api - 9.1.0` - I think updating that will help resolve some problems here.

**Comment by paulomarg** [comment] 2020-07-15 21:11
Hi @awd, great to hear it's working!

Regarding the old `shopify` binary, it was dropped from `shopify_api` on version 9.2.0, but `gem` doesn't delete it unless you actually uninstall `shopify_api` and reinstall it.

What does your `Gemfile.lock` file look like right now, specifically under the shopify_app section?

**Comment by awd** [comment] 2020-07-15 21:15
Hi @paulomarg - yeah I uninstalled it so saw it was removing the binary as well.

`shopify_api` is locked to 9.1.0 because of `shopify_app`:

`Gemfile.lock`
```
    shopify_app (13.4.0)
      browser_sniffer (~> 1.2.2)
      jwt (~> 2.2.1)
      omniauth-shopify-oauth2 (~> 2.2.2)
      rails (> 5.2.1)
      redirect_safely (~> 1.0)
      shopify_api (~> 9.1.0)
```

More verbose dependency issue here:
```
Bundler could not find compatible versions for gem "shopify_api":
  In Gemfile:
    shopify_api (~> 9.2)

    shopify_app (~> 13.4) was resolved to 13.4.0, which depends on
      shopify_api (~> 9.1.0)
```

Update `shopify_app` to bump the `shopify_api` gem - and it will go away.

**Comment by paulomarg** [comment] 2020-07-16 15:20
Hi @awd, `shopify_app` Release v13.4.1 is out now and it updates the dependency on `shopify_api`.

Hope that fixes the upgrade issues you had, and thanks for reporting this issue!

**Comment by awd** [comment] 2020-07-16 15:33
Hi @paulomarg - just tested this locally and can confirm it takes care of the issue yesterday as well.

Thank you!

**Comment by paulomarg** [comment] 2020-07-16 15:35
Closing this as it seems all reported issues were covered (thanks for the update @ShirasuGyoza!).

**Closed by paulomarg** 2020-07-16 15:35 UTC

**Comment by ShirasuGyoza** [comment] 2020-07-17 02:28
@paulomarg thank you!
